<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Het meester-gezel-principe een tijdloze m_7b8d40</name>
   <tag></tag>
   <elementGuidId>52c44a2d-2077-4d74-9d05-ff94b47a9c06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-25761']/div/div[2]/article/h4/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.uagb-post__title.uagb-post__text > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db4d0dcf-79a1-4bf5-b2aa-866438472a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/het-meester-gezel-principe-een-tijdloze-methode-voor-kennisdeling-en-groei/</value>
      <webElementGuid>71ace2ea-d2f7-4dff-b9ed-f807dd67099f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>e23c9a7e-ffa4-4633-8c1d-184c8fc146ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>bookmark noopener noreferrer</value>
      <webElementGuid>cb33f86a-14e9-4982-bb0f-22fbbe2cf311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Het meester-gezel-principe: een tijdloze methode voor kennisdeling en groei</value>
      <webElementGuid>33d5aa42-0d8f-46d9-bf41-d38868886c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-25761&quot;)/div[@class=&quot;entry-content clear&quot;]/div[@class=&quot;wp-block-uagb-post-grid uagb-post-grid  uagb-post__image-position-top uagb-post__image-enabled uagb-block-222e02ed     uagb-post__items uagb-post__columns-3 is-grid uagb-post__columns-tablet-2 uagb-post__columns-mobile-1 uagb-post__equal-height&quot;]/article[@class=&quot;uagb-post__inner-wrap&quot;]/h4[@class=&quot;uagb-post__title uagb-post__text&quot;]/a[1]</value>
      <webElementGuid>6c37391f-dfe8-4d5d-aa8d-274f1043f4e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-25761']/div/div[2]/article/h4/a</value>
      <webElementGuid>3d908e22-89cb-42ab-b2fe-536f098d99c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Het meester-gezel-principe: een tijdloze methode voor kennisdeling en groei')]</value>
      <webElementGuid>86994a83-4904-4212-8adc-fedcda8c8c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/het-meester-gezel-principe-een-tijdloze-methode-voor-kennisdeling-en-groei/')])[2]</value>
      <webElementGuid>aea3bc01-b097-400c-8ed2-9b60ac70940d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/a</value>
      <webElementGuid>b0a0937c-f8e5-4d1b-96ef-923dfb3a7c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/het-meester-gezel-principe-een-tijdloze-methode-voor-kennisdeling-en-groei/' and (text() = 'Het meester-gezel-principe: een tijdloze methode voor kennisdeling en groei' or . = 'Het meester-gezel-principe: een tijdloze methode voor kennisdeling en groei')]</value>
      <webElementGuid>9521c33e-31a7-4939-a2cf-7e50cbf7d92b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
