<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lees meer_1_2</name>
   <tag></tag>
   <elementGuidId>3095fa58-30b4-4ce4-bdd7-82cddaf955fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-25761']/div/div[2]/article[8]/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19066fbc-b5de-4ff5-8ebd-aef3af320d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-button__link uagb-text-link</value>
      <webElementGuid>1090408a-03fe-4d83-88ab-1b8bd7f55681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/nike-het-is-tof-om-te-werken-aan-een-systeem-met-een-maatschappelijke-rol/</value>
      <webElementGuid>d96e0af4-c8cf-4e89-b3e7-e72162d7715e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>f73b4c34-4860-4f59-8f94-a40836958581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>bookmark noopener noreferrer</value>
      <webElementGuid>9e1d6a88-a7e9-4113-a583-2bec9880bbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lees meer</value>
      <webElementGuid>0ddb91b8-bbfb-4647-8e9f-023b245e407c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-25761&quot;)/div[@class=&quot;entry-content clear&quot;]/div[@class=&quot;wp-block-uagb-post-grid uagb-post-grid  uagb-post__image-position-top uagb-post__image-enabled uagb-block-222e02ed     uagb-post__items uagb-post__columns-3 is-grid uagb-post__columns-tablet-2 uagb-post__columns-mobile-1 uagb-post__equal-height&quot;]/article[@class=&quot;uagb-post__inner-wrap&quot;]/div[@class=&quot;uagb-post__text uagb-post__cta wp-block-button&quot;]/a[@class=&quot;wp-block-button__link uagb-text-link&quot;]</value>
      <webElementGuid>ab738587-743b-4d01-9ad6-df6d7300d8fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-25761']/div/div[2]/article[8]/div[4]/a</value>
      <webElementGuid>ab1263bd-23be-417d-bbbc-931f1b126c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lees meer')])[8]</value>
      <webElementGuid>434725cc-045d-4ddb-a422-0dd5ef1a59fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/nike-het-is-tof-om-te-werken-aan-een-systeem-met-een-maatschappelijke-rol/')])[3]</value>
      <webElementGuid>a4a9c882-5411-40c7-ac89-ad99b98fa270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[8]/div[4]/a</value>
      <webElementGuid>c51d6a06-804b-4957-8236-d3c7317ba6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/nike-het-is-tof-om-te-werken-aan-een-systeem-met-een-maatschappelijke-rol/' and (text() = 'Lees meer' or . = 'Lees meer')]</value>
      <webElementGuid>34380dc8-576f-4dcb-be60-74580ae13811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
