<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lees meer</name>
   <tag></tag>
   <elementGuidId>8211e38f-8fe1-4834-828e-0f7b4a032a79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-25761']/div/div[2]/article[4]/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>31e035e3-0684-468b-8064-d50cb5041a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-button__link uagb-text-link</value>
      <webElementGuid>c623659e-2a20-48bf-977f-96666c374c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/de-kracht-van-agile-en-devops-in-testprocedures/</value>
      <webElementGuid>7723fc67-6816-4e9e-9952-6c12f8e74ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>545dd213-1c91-47d5-a73f-ecfacfc5cc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>bookmark noopener noreferrer</value>
      <webElementGuid>949adcc9-1a4f-47be-ac7e-8fa9b21e01b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lees meer</value>
      <webElementGuid>099f9652-610b-4436-9553-c7fe118daa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-25761&quot;)/div[@class=&quot;entry-content clear&quot;]/div[@class=&quot;wp-block-uagb-post-grid uagb-post-grid  uagb-post__image-position-top uagb-post__image-enabled uagb-block-222e02ed     uagb-post__items uagb-post__columns-3 is-grid uagb-post__columns-tablet-2 uagb-post__columns-mobile-1 uagb-post__equal-height&quot;]/article[@class=&quot;uagb-post__inner-wrap&quot;]/div[@class=&quot;uagb-post__text uagb-post__cta wp-block-button&quot;]/a[@class=&quot;wp-block-button__link uagb-text-link&quot;]</value>
      <webElementGuid>aa345e8c-3e64-4fe5-a541-d79d82c3ace1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-25761']/div/div[2]/article[4]/div[4]/a</value>
      <webElementGuid>aee667c0-0eb3-4c39-9e95-e91da13ba3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lees meer')])[4]</value>
      <webElementGuid>278d0bfe-ef7d-4baa-b288-0c9d7548ae26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/de-kracht-van-agile-en-devops-in-testprocedures/')])[3]</value>
      <webElementGuid>b1beffaf-a762-40bb-9b3f-aac64a82e7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[4]/div[4]/a</value>
      <webElementGuid>11c491f2-afc8-4e74-ae15-eb7eadf1a553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/de-kracht-van-agile-en-devops-in-testprocedures/' and (text() = 'Lees meer' or . = 'Lees meer')]</value>
      <webElementGuid>f7af6c2c-062f-4bb5-8b61-209bb380295c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
