<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lees meer_1</name>
   <tag></tag>
   <elementGuidId>cc4152d2-0d55-4c2e-a35c-61bd3419108c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-25761']/div/div[2]/article[7]/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bcfaa0a7-d6b6-4b45-8213-a0768b2e9368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-button__link uagb-text-link</value>
      <webElementGuid>6da11443-e30c-47ef-8755-ca4a93cc73ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/low-code-applicaties-hoef-je-niet-te-testen-feit-of-fabel/</value>
      <webElementGuid>ebbc3287-fc57-45b0-8329-83f1ae729ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>a139b79d-1f28-4247-b8f0-b1c72c0249a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>bookmark noopener noreferrer</value>
      <webElementGuid>315b399e-8f21-4105-b50e-c14ffd5baa22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lees meer</value>
      <webElementGuid>797f84da-d4f4-4f1c-906f-ca598e4f3dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-25761&quot;)/div[@class=&quot;entry-content clear&quot;]/div[@class=&quot;wp-block-uagb-post-grid uagb-post-grid  uagb-post__image-position-top uagb-post__image-enabled uagb-block-222e02ed     uagb-post__items uagb-post__columns-3 is-grid uagb-post__columns-tablet-2 uagb-post__columns-mobile-1 uagb-post__equal-height&quot;]/article[@class=&quot;uagb-post__inner-wrap&quot;]/div[@class=&quot;uagb-post__text uagb-post__cta wp-block-button&quot;]/a[@class=&quot;wp-block-button__link uagb-text-link&quot;]</value>
      <webElementGuid>b60cb556-dcd6-4dfe-b387-7286d13b5f26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-25761']/div/div[2]/article[7]/div[4]/a</value>
      <webElementGuid>e278d73f-1278-4aa4-a6db-0b77f21fd9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lees meer')])[7]</value>
      <webElementGuid>45414c90-8c63-478f-af73-a91799b9166c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/low-code-applicaties-hoef-je-niet-te-testen-feit-of-fabel/')])[3]</value>
      <webElementGuid>98f26ef2-9853-4c60-a4d5-7aec6c59263b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[7]/div[4]/a</value>
      <webElementGuid>eb0d1626-7be8-46a6-8795-e1d29cc80685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/low-code-applicaties-hoef-je-niet-te-testen-feit-of-fabel/' and (text() = 'Lees meer' or . = 'Lees meer')]</value>
      <webElementGuid>63d0a0bc-d65e-4fbc-b4ff-389f343fcdab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
