<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Testen is alleen nodig bij complexe softw_ca2eec</name>
   <tag></tag>
   <elementGuidId>2b03c9b8-8d1f-4ff7-a0ae-e9dff421cc0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-25761']/div/div[2]/article[3]/h4/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a093168f-8f2b-47a0-9877-8fb0e7e12c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/testen-is-alleen-nodig-bij-complexe-softwareprojecten-fabel-of-feit/</value>
      <webElementGuid>9eb25513-628c-46ed-b333-4c1b40753fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>bbd27d15-9b4a-47d9-ad8e-c2bff7e0cc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>bookmark noopener noreferrer</value>
      <webElementGuid>8f3c9523-75a3-48d9-bfd9-cba5fcdfb5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testen is alleen nodig bij complexe softwareprojecten. Fabel of feit?</value>
      <webElementGuid>6c8c615c-1287-46db-bbce-ee78cbc11519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-25761&quot;)/div[@class=&quot;entry-content clear&quot;]/div[@class=&quot;wp-block-uagb-post-grid uagb-post-grid  uagb-post__image-position-top uagb-post__image-enabled uagb-block-222e02ed     uagb-post__items uagb-post__columns-3 is-grid uagb-post__columns-tablet-2 uagb-post__columns-mobile-1 uagb-post__equal-height&quot;]/article[@class=&quot;uagb-post__inner-wrap&quot;]/h4[@class=&quot;uagb-post__title uagb-post__text&quot;]/a[1]</value>
      <webElementGuid>cb6de932-28fc-4028-8cb8-21187343f3dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-25761']/div/div[2]/article[3]/h4/a</value>
      <webElementGuid>42cf08c5-4ec0-402a-aa67-02de7a3b5bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Testen is alleen nodig bij complexe softwareprojecten. Fabel of feit?')]</value>
      <webElementGuid>28e917b1-09e1-4d8b-a3b5-a7b17c6b77fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/testen-is-alleen-nodig-bij-complexe-softwareprojecten-fabel-of-feit/')])[2]</value>
      <webElementGuid>06cbd65f-e898-4407-a5b5-cd1b9bbfd2d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[3]/h4/a</value>
      <webElementGuid>acf74a65-2aa5-42c3-a233-58cc560e2683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/testen-is-alleen-nodig-bij-complexe-softwareprojecten-fabel-of-feit/' and (text() = 'Testen is alleen nodig bij complexe softwareprojecten. Fabel of feit?' or . = 'Testen is alleen nodig bij complexe softwareprojecten. Fabel of feit?')]</value>
      <webElementGuid>d6ad0f94-e918-4f43-bc02-db3e7d8da40a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
