<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_attachment-large size-large entered lazyloaded_1_2</name>
   <tag></tag>
   <elementGuidId>6b390824-5d93-48f2-a846-1f9e9db7c88f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-25761']/div/div[2]/article[6]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aed8bbb7-2f17-4cde-b3dd-a5ac0ea0ca2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>676375b8-c1b0-46c8-9cd9-0d98d7e33cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>512</value>
      <webElementGuid>bcf4eaaf-7ae2-473c-ae49-f63978107c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/08/shutterstock_1674488725-1-1024x512.jpg</value>
      <webElementGuid>122797d9-2c8c-4bd5-9a21-864938af8018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large entered lazyloaded</value>
      <webElementGuid>646abd46-4e09-447c-86ff-1c9c47695b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>De invloed van VR en AR op testprocedures</value>
      <webElementGuid>add7d8da-0db6-4564-9d32-612a0334cfd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>21b55a92-6215-48d5-b295-6c73e491fd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/08/shutterstock_1674488725-1-1024x512.jpg 1024w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/08/shutterstock_1674488725-1-300x150.jpg 300w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/08/shutterstock_1674488725-1-768x384.jpg 768w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/08/shutterstock_1674488725-1.jpg 1200w</value>
      <webElementGuid>51fee8af-db29-4f95-bdc1-1c2274b41b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-sizes</name>
      <type>Main</type>
      <value>(max-width: 1024px) 100vw, 1024px</value>
      <webElementGuid>beb6ca26-9bb9-44ed-8ef2-767e7e1c6a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/08/shutterstock_1674488725-1-1024x512.jpg</value>
      <webElementGuid>3fdd3e80-7f77-46b7-a758-cbd8addaf84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>ab42f50e-aaf2-4eaf-9ebc-1e3b53c11fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 1024px) 100vw, 1024px</value>
      <webElementGuid>dc7c6f5e-9310-46bd-b678-b15a6dc588fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/08/shutterstock_1674488725-1-1024x512.jpg 1024w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/08/shutterstock_1674488725-1-300x150.jpg 300w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/08/shutterstock_1674488725-1-768x384.jpg 768w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/08/shutterstock_1674488725-1.jpg 1200w</value>
      <webElementGuid>6c826064-be61-420a-9184-5937d3f6aaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-25761&quot;)/div[@class=&quot;entry-content clear&quot;]/div[@class=&quot;wp-block-uagb-post-grid uagb-post-grid  uagb-post__image-position-top uagb-post__image-enabled uagb-block-222e02ed     uagb-post__items uagb-post__columns-3 is-grid uagb-post__columns-tablet-2 uagb-post__columns-mobile-1 uagb-post__equal-height&quot;]/article[@class=&quot;uagb-post__inner-wrap&quot;]/div[@class=&quot;uagb-post__image&quot;]/a[@class=&quot;uagb-image-ratio-inherit&quot;]/img[@class=&quot;attachment-large size-large entered lazyloaded&quot;]</value>
      <webElementGuid>f6a85461-ca40-4fcf-a378-d269defbee82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-25761']/div/div[2]/article[6]/div/a/img</value>
      <webElementGuid>288aed3f-6b33-4162-84f4-78bed03342a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='De invloed van VR en AR op testprocedures']</value>
      <webElementGuid>3ae37072-c185-4afe-a15e-b10f1701d7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[6]/div/a/img</value>
      <webElementGuid>75e9d459-795c-4c30-a634-96799f352099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/08/shutterstock_1674488725-1-1024x512.jpg' and @alt = 'De invloed van VR en AR op testprocedures']</value>
      <webElementGuid>3d668133-4477-41f2-863f-305fbe4410e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
