<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_attachment-large size-large entered lazyloaded_1</name>
   <tag></tag>
   <elementGuidId>00a58617-f66f-460b-b80b-449cad0f46ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-25761']/div/div[2]/article[5]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>62fbe576-3695-45c5-854a-1ef67bfef4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>a45b55b8-496c-45b0-9a4c-8bcfcb81abab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>512</value>
      <webElementGuid>43369737-fd6b-4ec0-a528-411bc038df8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/09/shutterstock_333763337-1-1024x512.jpg</value>
      <webElementGuid>9a0df80e-c468-4900-995a-200cd2d787c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large entered lazyloaded</value>
      <webElementGuid>b8145add-3a9b-4891-8267-5de359c8efe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>De voor- en nadelen van testautomatisering</value>
      <webElementGuid>605c90c6-b4f0-4174-b76d-42e89390a9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>d7a81e19-39e1-4180-a7b7-511d9b2a724c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/09/shutterstock_333763337-1-1024x512.jpg 1024w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/09/shutterstock_333763337-1-300x150.jpg 300w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/09/shutterstock_333763337-1-768x384.jpg 768w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/09/shutterstock_333763337-1.jpg 1200w</value>
      <webElementGuid>29c21194-595e-43e0-bcf6-e9443fac4573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-sizes</name>
      <type>Main</type>
      <value>(max-width: 1024px) 100vw, 1024px</value>
      <webElementGuid>75e40132-ec52-4012-a99c-ac7d818c8037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/09/shutterstock_333763337-1-1024x512.jpg</value>
      <webElementGuid>cb33342c-7a5e-45c1-b536-36d82f390848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>3c98e6c8-0863-409e-ab62-83a126575e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 1024px) 100vw, 1024px</value>
      <webElementGuid>72e24b1c-29de-4adf-b9b2-b9dac74b5d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/09/shutterstock_333763337-1-1024x512.jpg 1024w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/09/shutterstock_333763337-1-300x150.jpg 300w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/09/shutterstock_333763337-1-768x384.jpg 768w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/09/shutterstock_333763337-1.jpg 1200w</value>
      <webElementGuid>aba77996-6fd9-468f-814a-67986d8b65b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-25761&quot;)/div[@class=&quot;entry-content clear&quot;]/div[@class=&quot;wp-block-uagb-post-grid uagb-post-grid  uagb-post__image-position-top uagb-post__image-enabled uagb-block-222e02ed     uagb-post__items uagb-post__columns-3 is-grid uagb-post__columns-tablet-2 uagb-post__columns-mobile-1 uagb-post__equal-height&quot;]/article[@class=&quot;uagb-post__inner-wrap&quot;]/div[@class=&quot;uagb-post__image&quot;]/a[@class=&quot;uagb-image-ratio-inherit&quot;]/img[@class=&quot;attachment-large size-large entered lazyloaded&quot;]</value>
      <webElementGuid>aad098e9-ea90-4225-bf67-f63a8b954449</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-25761']/div/div[2]/article[5]/div/a/img</value>
      <webElementGuid>25eaff2a-ced0-4ac4-99a2-bf5cdd82d640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='De voor- en nadelen van testautomatisering']</value>
      <webElementGuid>4afcee48-d196-4f91-bbdd-b9d1e7af2043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[5]/div/a/img</value>
      <webElementGuid>2dbf0b8d-2db9-4849-9908-b04a941532d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/09/shutterstock_333763337-1-1024x512.jpg' and @alt = 'De voor- en nadelen van testautomatisering']</value>
      <webElementGuid>a6527ee0-28d9-4c9b-a476-cf3f5141f2e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
