<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_attachment-large size-large entered lazyloaded_1_2_3</name>
   <tag></tag>
   <elementGuidId>da9a3fa6-bd41-41b3-a10a-2d5c20c340fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-25761']/div/div[2]/article[9]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9c932ab2-01cb-41fd-b636-9380df24ac0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>fb4edf6a-d318-4542-9ae2-c130a1d6194f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>512</value>
      <webElementGuid>fcbb9fd3-6e57-4e0b-99a0-a285711de85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/07/shutterstock_253676299-1-1024x512.jpg</value>
      <webElementGuid>180dc138-dc59-4ccc-ba05-69b1c28278ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large entered lazyloaded</value>
      <webElementGuid>0d7e6520-5060-4e27-826a-fe5f9c8067d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Automatisch of handmatig testen: efficiëntie versus menselijke touch</value>
      <webElementGuid>eb11c9fb-726f-497e-8bf5-254d018df20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>405cdbd6-ffab-437b-93eb-90a3a6b5dc08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/07/shutterstock_253676299-1-1024x512.jpg 1024w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/07/shutterstock_253676299-1-300x150.jpg 300w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/07/shutterstock_253676299-1-768x384.jpg 768w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/07/shutterstock_253676299-1.jpg 1200w</value>
      <webElementGuid>2c497812-d727-4f1b-85ce-495253b698cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-sizes</name>
      <type>Main</type>
      <value>(max-width: 1024px) 100vw, 1024px</value>
      <webElementGuid>50142ee1-01e0-4390-86ff-f80cb9294240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/07/shutterstock_253676299-1-1024x512.jpg</value>
      <webElementGuid>ef604aa3-cee7-40b5-a4dc-834f3aa37519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>2499665f-506e-4c73-b9af-352e66ce540f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 1024px) 100vw, 1024px</value>
      <webElementGuid>a64eede9-0bc2-4fa1-9751-4615ff9b4c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/07/shutterstock_253676299-1-1024x512.jpg 1024w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/07/shutterstock_253676299-1-300x150.jpg 300w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/07/shutterstock_253676299-1-768x384.jpg 768w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/07/shutterstock_253676299-1.jpg 1200w</value>
      <webElementGuid>41b333df-9493-402c-9be2-390232a20299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-25761&quot;)/div[@class=&quot;entry-content clear&quot;]/div[@class=&quot;wp-block-uagb-post-grid uagb-post-grid  uagb-post__image-position-top uagb-post__image-enabled uagb-block-222e02ed     uagb-post__items uagb-post__columns-3 is-grid uagb-post__columns-tablet-2 uagb-post__columns-mobile-1 uagb-post__equal-height&quot;]/article[@class=&quot;uagb-post__inner-wrap&quot;]/div[@class=&quot;uagb-post__image&quot;]/a[@class=&quot;uagb-image-ratio-inherit&quot;]/img[@class=&quot;attachment-large size-large entered lazyloaded&quot;]</value>
      <webElementGuid>56f1df12-fda5-4af3-800f-f06e0d02505f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-25761']/div/div[2]/article[9]/div/a/img</value>
      <webElementGuid>3bf9a5fc-693f-4b03-af6f-33bb4f8f4d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Automatisch of handmatig testen: efficiëntie versus menselijke touch']</value>
      <webElementGuid>76adb859-028d-483c-bc55-94031971fb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[9]/div/a/img</value>
      <webElementGuid>c05d559c-057c-4a6f-bc81-c8bb49596e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/07/shutterstock_253676299-1-1024x512.jpg' and @alt = 'Automatisch of handmatig testen: efficiëntie versus menselijke touch']</value>
      <webElementGuid>39f2a74c-6a75-4236-b093-65084a0caaa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
