<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_attachment-large size-large entered lazyloaded</name>
   <tag></tag>
   <elementGuidId>7356f781-f9f1-4faf-b79a-33cf6a086ab6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-25761']/div/div[2]/article[2]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1e92a79d-4889-484c-8884-2afc6934cb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>943598de-ab81-4be7-9dc8-f3a86ba4403b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>512</value>
      <webElementGuid>0004efdb-3358-4f7d-ace5-5aeeedd5efe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/10/shutterstock_2311033987-1-1024x512.jpg</value>
      <webElementGuid>27c692bd-deea-4d77-abe2-ac811e439473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large entered lazyloaded</value>
      <webElementGuid>b6b93334-3e64-4f4e-b7e6-712eed8e8d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Het belang van UX en de waarde van een UX-lab</value>
      <webElementGuid>43d7018c-9a83-4e2f-9620-0f00b5b7120f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>f7bc29b0-5a83-4acd-96ff-6a73b4f3d014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/10/shutterstock_2311033987-1-1024x512.jpg 1024w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/10/shutterstock_2311033987-1-300x150.jpg 300w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/10/shutterstock_2311033987-1-768x384.jpg 768w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/10/shutterstock_2311033987-1.jpg 1200w</value>
      <webElementGuid>ed05945c-8006-4eeb-922b-69fcac3dd6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-sizes</name>
      <type>Main</type>
      <value>(max-width: 1024px) 100vw, 1024px</value>
      <webElementGuid>e1c8bf04-379a-40c4-af0e-0fc78d6b2a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/10/shutterstock_2311033987-1-1024x512.jpg</value>
      <webElementGuid>48fed118-7696-4574-9e03-a8ab6bebc3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>5388517a-63bd-4243-8d95-e3103332e9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 1024px) 100vw, 1024px</value>
      <webElementGuid>d28b475c-f524-46b1-b62d-6b15f70dbb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/10/shutterstock_2311033987-1-1024x512.jpg 1024w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/10/shutterstock_2311033987-1-300x150.jpg 300w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/10/shutterstock_2311033987-1-768x384.jpg 768w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/10/shutterstock_2311033987-1.jpg 1200w</value>
      <webElementGuid>41fdfe50-fc95-4d50-bc1e-788751c8c6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-25761&quot;)/div[@class=&quot;entry-content clear&quot;]/div[@class=&quot;wp-block-uagb-post-grid uagb-post-grid  uagb-post__image-position-top uagb-post__image-enabled uagb-block-222e02ed     uagb-post__items uagb-post__columns-3 is-grid uagb-post__columns-tablet-2 uagb-post__columns-mobile-1 uagb-post__equal-height&quot;]/article[@class=&quot;uagb-post__inner-wrap&quot;]/div[@class=&quot;uagb-post__image&quot;]/a[@class=&quot;uagb-image-ratio-inherit&quot;]/img[@class=&quot;attachment-large size-large entered lazyloaded&quot;]</value>
      <webElementGuid>320e7450-32e1-49cb-9942-25d2d64a7716</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-25761']/div/div[2]/article[2]/div/a/img</value>
      <webElementGuid>c4894795-0b1e-44ba-8c32-fb7b2028e296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Het belang van UX en de waarde van een UX-lab']</value>
      <webElementGuid>816e89dd-50df-4f65-adcc-9b2b015cbda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[2]/div/a/img</value>
      <webElementGuid>702a0586-4d09-4d31-8e3c-64830fa875d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2023/10/shutterstock_2311033987-1-1024x512.jpg' and @alt = 'Het belang van UX en de waarde van een UX-lab']</value>
      <webElementGuid>4fbfbe03-aa8d-41ea-af58-d76309e519b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
