<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Cases</name>
   <tag></tag>
   <elementGuidId>f9dcc2d1-2ae4-4b9f-8ca6-32d66a09ee2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='block-3']/div/div[2]/p[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bf307fc4-cd0e-4f0c-84ee-28e27bb01e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/cases/</value>
      <webElementGuid>a86e047d-16b7-4fa3-8d6f-e79c8ca6aaaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>a523e562-bdc7-4c37-89cc-9c4a740f48ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>25798</value>
      <webElementGuid>ac50652f-b879-447e-9355-6f4e69a28f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cases</value>
      <webElementGuid>3e1efc76-1904-49ad-9005-48a76fefbc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-3&quot;)/div[@class=&quot;is-layout-flex wp-container-12 wp-block-columns&quot;]/div[@class=&quot;is-layout-flow wp-block-column&quot;]/p[4]/a[1]</value>
      <webElementGuid>b78f2ee7-92e4-49c8-b637-a54b36f8aad2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='block-3']/div/div[2]/p[4]/a</value>
      <webElementGuid>7bcaba2e-dfda-4e8d-80b9-406b86e8e3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cases')]</value>
      <webElementGuid>b685ffe7-c3ff-45a3-8976-6f43d714cb91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/cases/')]</value>
      <webElementGuid>6bbf0153-03e4-411e-bd52-2348f8e628ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/a</value>
      <webElementGuid>6fe4f706-7a35-437f-92f8-f1c38e5e1733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/cases/' and (text() = 'Cases' or . = 'Cases')]</value>
      <webElementGuid>e2ba0ec9-2220-4952-8c50-930143f7d91b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
