<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Blog</name>
   <tag></tag>
   <elementGuidId>d38df694-80ae-4463-beae-0c8f1bfde46e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='block-3']/div/div[2]/p[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(5) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a6d54ed-702b-4c7c-be64-a1a5f70b5db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/blog/</value>
      <webElementGuid>9a4ce660-5763-4904-9f22-807f20e511a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>4667d651-9636-4623-8db1-99c0dff0d6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>25761</value>
      <webElementGuid>3451c311-8a5b-4caa-8003-8601e1ef880e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blog</value>
      <webElementGuid>fd49c113-e925-4b35-9acf-c3880972b075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-3&quot;)/div[@class=&quot;is-layout-flex wp-container-12 wp-block-columns&quot;]/div[@class=&quot;is-layout-flow wp-block-column&quot;]/p[5]/a[1]</value>
      <webElementGuid>34a4afef-fbe3-4d09-9719-5b357d38b5e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='block-3']/div/div[2]/p[5]/a</value>
      <webElementGuid>8adbf677-4bc7-4aac-b480-c49d03ca7bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Blog')])[3]</value>
      <webElementGuid>a82a283d-d2fc-4247-859f-19b810126f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/blog/')])[3]</value>
      <webElementGuid>cec08c89-73cd-4fc0-9578-5516e93af457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/a</value>
      <webElementGuid>205d9000-066f-4e79-bc8a-da0c6654f059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/blog/' and (text() = 'Blog' or . = 'Blog')]</value>
      <webElementGuid>d3aa31d7-9bab-44c9-b04f-0d842e306421</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
