<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Privacybeleid</name>
   <tag></tag>
   <elementGuidId>a32c0b27-4e94-4a09-8cfb-c36034c9056b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='block-3']/div[5]/p[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>581aca7d-2afb-429e-9e43-1ed4d2969f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/privacybeleid/</value>
      <webElementGuid>418a3ee8-e810-46fc-838c-58abcb75fae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privacybeleid</value>
      <webElementGuid>48006bf5-d8bd-46c2-a54d-c81aa1d98f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-3&quot;)/div[@class=&quot;is-content-justification-center is-nowrap is-layout-flex wp-container-14 wp-block-group&quot;]/p[@class=&quot;has-small-font-size&quot;]/a[1]</value>
      <webElementGuid>c7052b07-c82f-48bb-bdb3-f4ed707d91b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='block-3']/div[5]/p[3]/a</value>
      <webElementGuid>a127f061-e677-43d7-b0b9-c84390b32761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Privacybeleid')]</value>
      <webElementGuid>d0f8bc34-a245-44ec-bb6e-dc30dc8db1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/privacybeleid/')]</value>
      <webElementGuid>7028d5f5-b4bb-446e-98d5-5c12373f05b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/p[3]/a</value>
      <webElementGuid>576b5580-b880-4922-abe0-f6b6c6f89040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/privacybeleid/' and (text() = 'Privacybeleid' or . = 'Privacybeleid')]</value>
      <webElementGuid>83666e9a-5d64-4a38-88b1-f3df6e949947</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
