<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_socials_Facebook</name>
   <tag></tag>
   <elementGuidId>1f4ec2df-92dd-485e-8a57-981c48bd2e92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='block-3']/ul/li[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.wp-block-social-link-anchor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17f9b4ae-7feb-4eed-a65b-c1a7c8154ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.facebook.com/risqitbv/</value>
      <webElementGuid>bba3465d-6c89-47ad-9988-5e6f0b36e200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener nofollow</value>
      <webElementGuid>34760920-080e-465a-a828-abdbbed933f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>ac2e82ac-03b8-47e2-aaae-b952914b53a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-social-link-anchor</value>
      <webElementGuid>2d9cbb4a-9f42-4864-804f-64df6afb7089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>risqitbv</value>
      <webElementGuid>01a809bc-ba56-495c-afd2-8d26ecea8183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-3&quot;)/ul[@class=&quot;is-layout-flex wp-block-social-links aligncenter has-normal-icon-size has-visible-labels has-icon-color is-style-logos-only&quot;]/li[@class=&quot;wp-social-link wp-social-link-facebook wp-block-social-link&quot;]/a[@class=&quot;wp-block-social-link-anchor&quot;]</value>
      <webElementGuid>fa62233a-9d82-42a4-ae24-23e9e763b41e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='block-3']/ul/li[1]/a</value>
      <webElementGuid>fcb405c4-a9ce-4eb3-bf6d-1b7ae98007b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.facebook.com/risqitbv/')]</value>
      <webElementGuid>a5193ca0-94cc-4dd6-87c9-2d95d2d7ee48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li/a</value>
      <webElementGuid>0bc2663b-fcc7-4bcf-adcc-d24461513a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.facebook.com/risqitbv/' and (text() = 'risqitbv' or . = 'risqitbv')]</value>
      <webElementGuid>965b2896-0baf-4508-848c-9d80d9f11d7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
