<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Telnr</name>
   <tag></tag>
   <elementGuidId>a273baca-11c9-402a-9676-7bbe15ab22cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='block-3']/div/div/div/div[2]/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.alt-link > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7a5b135b-4765-4d5d-83eb-35ea7f83efe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>tel:+31646407026</value>
      <webElementGuid>5898f390-d7b8-4cc8-a74d-a018b84e65f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+31(0)6 46 40 70 26</value>
      <webElementGuid>2372f076-4a35-49cd-b415-5461e8775089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-3&quot;)/div[@class=&quot;is-layout-flex wp-container-12 wp-block-columns&quot;]/div[@class=&quot;is-layout-flow wp-block-column&quot;]/div[@class=&quot;is-layout-flex wp-container-8 wp-block-columns&quot;]/div[@class=&quot;is-layout-flow wp-block-column&quot;]/p[@class=&quot;alt-link&quot;]/a[1]</value>
      <webElementGuid>02de95f4-822e-4d52-bacb-44659d5d67fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='block-3']/div/div/div/div[2]/p/a</value>
      <webElementGuid>9c3c4d82-7628-4aa1-b733-7f34a40d0ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'+31(0)6 46 40 70 26')]</value>
      <webElementGuid>952a8fef-1818-420f-831b-0ac3fd17541c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'tel:+31646407026')]</value>
      <webElementGuid>f12fabe3-cfeb-4953-96e5-8d50cd995101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>c3f55e1b-aaa0-441a-8f4c-de7d1371c3e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'tel:+31646407026' and (text() = '+31(0)6 46 40 70 26' or . = '+31(0)6 46 40 70 26')]</value>
      <webElementGuid>ad56af8b-8d28-4b3b-9995-648ba6b1e051</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
