<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_UXLab</name>
   <tag></tag>
   <elementGuidId>83044586-7ca7-4329-a0b9-be4a37bf84e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='block-3']/div/div[3]/p[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ad4bd74-620e-4a11-afba-0a8712f764a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/ux-lab/</value>
      <webElementGuid>ec4fcc95-46f1-45d9-bf83-6495755d2fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>84693b8f-e8f5-46c9-83d3-413e0dbbd2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>0226bf6d-ad37-4194-85b5-a9815f675b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UX Lab</value>
      <webElementGuid>a1b027f7-be84-46f9-b0f1-4f1c7c52e268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-3&quot;)/div[@class=&quot;is-layout-flex wp-container-12 wp-block-columns&quot;]/div[@class=&quot;is-layout-flow wp-block-column&quot;]/p[4]/a[1]</value>
      <webElementGuid>871c478e-a116-46e1-889f-089a63cd148a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='block-3']/div/div[3]/p[4]/a</value>
      <webElementGuid>dbe72f79-3aef-4929-ae51-d3fb8b56f62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'UX Lab')])[3]</value>
      <webElementGuid>b92caf13-927a-4d90-8673-ff7a71937c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/ux-lab/')])[4]</value>
      <webElementGuid>420e847b-6732-4337-bb63-e9b3806b699f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p[4]/a</value>
      <webElementGuid>d7112acf-950d-4cc9-a3ea-7354f5990b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/ux-lab/' and (text() = 'UX Lab' or . = 'UX Lab')]</value>
      <webElementGuid>8e4fb9b4-82f0-4a06-b596-ca1d378367b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
