<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_FreeTest</name>
   <tag></tag>
   <elementGuidId>6a264f55-2ad5-4e00-886d-55cdb89f693d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='block-3']/div/div/figure[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.wp-image-312.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>71fe21e6-9544-4744-9d48-ebcf1fafc526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>4225043e-5595-446c-80ac-3666cfc4a1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>154</value>
      <webElementGuid>58b842b0-836d-48f1-b833-5da8024d9e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>47</value>
      <webElementGuid>b4f26874-9b7d-48a4-ba73-857b9fc02d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2020/07/freetest.png</value>
      <webElementGuid>f1411aa1-83b8-4adb-9014-4695c926b33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-image-312 entered lazyloaded</value>
      <webElementGuid>f7b09f80-748b-42b1-9b10-07995207d799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2020/07/freetest.png 154w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2020/07/freetest-150x47.png 150w</value>
      <webElementGuid>399bfbc9-3b44-46a6-8ed1-32e3a3842548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-sizes</name>
      <type>Main</type>
      <value>(max-width: 154px) 100vw, 154px</value>
      <webElementGuid>be848ec2-4e29-45ae-8e75-3e5b72e6f336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2020/07/freetest.png</value>
      <webElementGuid>456f994c-828e-44b6-98d6-aeff280bccd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>6f0fd682-9a2f-4be2-b456-893cbdf2f393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 154px) 100vw, 154px</value>
      <webElementGuid>8f74c249-a7d2-43e8-b510-e79c0f3dd11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2020/07/freetest.png 154w, https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2020/07/freetest-150x47.png 150w</value>
      <webElementGuid>b5d243c6-fe67-4d05-80f1-bd32fcc5ed50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-3&quot;)/div[@class=&quot;is-layout-flex wp-container-12 wp-block-columns&quot;]/div[@class=&quot;is-layout-flow wp-block-column&quot;]/figure[@class=&quot;wp-block-image size-full&quot;]/a[1]/img[@class=&quot;wp-image-312 entered lazyloaded&quot;]</value>
      <webElementGuid>6a5b7d74-03dd-428b-8b76-1849e27c4d25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='block-3']/div/div/figure[2]/a</value>
      <webElementGuid>0aa77af8-2830-4517-bb24-6259e7ad97d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2020/07/freetest.png')]</value>
      <webElementGuid>824c1d36-0450-46c4-9c29-ef4013609a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure[2]/a/img</value>
      <webElementGuid>6557f76f-b3ce-47b9-85ea-9b0a905ddc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2020/07/freetest.png']</value>
      <webElementGuid>3d4cf61a-f13e-4ea1-bf62-985deca6b8a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
