<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_socials_LinkedIn</name>
   <tag></tag>
   <elementGuidId>e59f2dd0-3616-41e6-856a-2668abc09020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='block-3']/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.wp-social-link.wp-social-link-linkedin.wp-block-social-link > a.wp-block-social-link-anchor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>66b3fe41-f29e-49c5-85ea-df1e81bf8cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://linkedin.com/company/risqit-bv</value>
      <webElementGuid>d34c529a-34db-4dab-86c2-c68c790d43f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener nofollow</value>
      <webElementGuid>b587f561-9f65-4328-aba4-f1ac4dfcc2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a457fcf8-3561-4de2-9324-a4f0187738c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-social-link-anchor</value>
      <webElementGuid>7c3c20bf-3b8f-4eb4-a170-df93b52d8ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>risqit-bv</value>
      <webElementGuid>7dd9ca36-5df8-4a8e-881a-b1109a68a080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-3&quot;)/ul[@class=&quot;is-layout-flex wp-block-social-links aligncenter has-normal-icon-size has-visible-labels has-icon-color is-style-logos-only&quot;]/li[@class=&quot;wp-social-link wp-social-link-linkedin wp-block-social-link&quot;]/a[@class=&quot;wp-block-social-link-anchor&quot;]</value>
      <webElementGuid>c27a4414-7bbf-4607-b413-9fe1c06ee87d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='block-3']/ul/li[5]/a</value>
      <webElementGuid>897b2c10-4ed3-43d7-973e-e4cf8c44ccfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://linkedin.com/company/risqit-bv')]</value>
      <webElementGuid>c61990f2-73bf-4b64-850b-b13ea0d69ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>91d70413-5c4e-4397-911c-c23375c9977a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://linkedin.com/company/risqit-bv' and (text() = 'risqit-bv' or . = 'risqit-bv')]</value>
      <webElementGuid>aee483de-655a-481d-81ee-673f6a15e05b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
