<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_socials_Insta</name>
   <tag></tag>
   <elementGuidId>576e8d1d-4f9e-41b9-bb37-0816f18ebdd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='block-3']/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.wp-social-link.wp-social-link-instagram.wp-block-social-link > a.wp-block-social-link-anchor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a3873ca-f02e-408c-b745-bb0683b3e584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.instagram.com/risqitinsta/</value>
      <webElementGuid>0125b02b-8225-4937-8448-aac0689ea583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener nofollow</value>
      <webElementGuid>72a6900f-0a25-4900-8799-cfb316b4f5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>7d1879bb-a8e5-4ba4-9bd0-2a6a9ef1e60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-social-link-anchor</value>
      <webElementGuid>cebb2e13-4f96-4b73-8d2e-104a5cd403fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>risqitinsta</value>
      <webElementGuid>7ecca245-7230-4b38-8920-8d754f87f26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-3&quot;)/ul[@class=&quot;is-layout-flex wp-block-social-links aligncenter has-normal-icon-size has-visible-labels has-icon-color is-style-logos-only&quot;]/li[@class=&quot;wp-social-link wp-social-link-instagram wp-block-social-link&quot;]/a[@class=&quot;wp-block-social-link-anchor&quot;]</value>
      <webElementGuid>956e857b-7736-4824-932d-02f552c95dff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='block-3']/ul/li[4]/a</value>
      <webElementGuid>19316f66-7fc0-4fd9-89a0-1849930fea10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.instagram.com/risqitinsta/')]</value>
      <webElementGuid>e9fb2376-dd00-4719-9d83-7c83add2ea59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li[4]/a</value>
      <webElementGuid>3102d1ae-ee93-4757-8a8f-0c1440fd0da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.instagram.com/risqitinsta/' and (text() = 'risqitinsta' or . = 'risqitinsta')]</value>
      <webElementGuid>ef692fd1-9c11-4f56-9747-3b97ca9be2b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
