<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_infoATrisqit.nl</name>
   <tag></tag>
   <elementGuidId>20d34bb8-0f88-4dd1-a49d-c9041d6ae1ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='block-3']/div/div/div/div[2]/p[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4203c574-eb68-4c90-b368-6e8c2109b36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:info@risqit.nl</value>
      <webElementGuid>213ed199-61c7-4d51-b443-ab55198561fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>info@risqit.nl</value>
      <webElementGuid>f33d3aac-c90d-4034-be42-690b82926785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-3&quot;)/div[@class=&quot;is-layout-flex wp-container-12 wp-block-columns&quot;]/div[@class=&quot;is-layout-flow wp-block-column&quot;]/div[@class=&quot;is-layout-flex wp-container-8 wp-block-columns&quot;]/div[@class=&quot;is-layout-flow wp-block-column&quot;]/p[@class=&quot;alt-link&quot;]/a[1]</value>
      <webElementGuid>d3dea69f-252a-4095-b728-9dfb5becac9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='block-3']/div/div/div/div[2]/p[2]/a</value>
      <webElementGuid>095f0269-c5a7-46f9-bb03-ef142f9c4d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'info@risqit.nl')]</value>
      <webElementGuid>29c9197e-6b1a-4984-aba6-fdfc973b3cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:info@risqit.nl')]</value>
      <webElementGuid>60a17429-c85b-4dc1-b41f-3b68ef72dfb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>d1187d7e-29aa-4f3e-9c03-d89c35ebaab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:info@risqit.nl' and (text() = 'info@risqit.nl' or . = 'info@risqit.nl')]</value>
      <webElementGuid>c9ddae80-ed29-4342-bd4c-244747a06922</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
