<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_UX Lab</name>
   <tag></tag>
   <elementGuidId>0550ac65-dea3-4922-9034-112ae841ecc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-324']/header/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.entry-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f535ee24-0da6-419b-903c-46ad0c723dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entry-title</value>
      <webElementGuid>f8fda303-9c56-4485-bc1e-940e0183da98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>headline</value>
      <webElementGuid>559bddc6-845b-49eb-a491-17e44e68b33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UX Lab</value>
      <webElementGuid>ca6d5485-1ac5-4ca6-a46d-83d8d9199667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-324&quot;)/header[@class=&quot;entry-header ast-no-thumbnail&quot;]/h1[@class=&quot;entry-title&quot;]</value>
      <webElementGuid>4ebcb290-fde9-4201-a86a-9bb90478cd9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-324']/header/h1</value>
      <webElementGuid>674804f5-9aa5-4031-b68c-c95d4b2a41a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>ad217faa-6507-4f0d-9587-f97695cc10e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'UX Lab' or . = 'UX Lab')]</value>
      <webElementGuid>5753e311-7c93-4535-81a8-ab531e7ba5de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
