<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_custom-logo entered lazyloaded</name>
   <tag></tag>
   <elementGuidId>0d82ab8d-a9e0-4835-ae8d-6b6deeaf2e13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ast-desktop-header']/div/div/div/div/div/div/div/span/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.custom-logo.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dfa22c05-6b7a-407b-9b2c-dd79164187f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>174</value>
      <webElementGuid>8d0aedd2-de82-4f86-b625-d98365f0b51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>51</value>
      <webElementGuid>5934f5fe-9f19-4f1a-bdcb-1dfa1ce92324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2022/12/risqitlogo22-e1671873581192.png</value>
      <webElementGuid>d0a745c2-54f2-4efb-9bb6-7ccc0a218397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-logo entered lazyloaded</value>
      <webElementGuid>b1d49d1e-2737-486d-af12-68d83af28587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>RisQIT</value>
      <webElementGuid>7b32ebd1-4f65-4d16-b8d5-5915a004e338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>09fe6ea1-652a-4ecb-a171-a4c22a9ec89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2022/12/risqitlogo22-e1671873581192.png</value>
      <webElementGuid>6198d192-6d1d-4fcc-989c-1525945c4b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>ce8d0604-d49c-40e2-aa0b-34854b30b1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ast-desktop-header&quot;)/div[@class=&quot;ast-main-header-wrap main-header-bar-wrap&quot;]/div[@class=&quot;ast-primary-header-bar ast-primary-header main-header-bar site-header-focus-item&quot;]/div[@class=&quot;site-primary-header-wrap ast-builder-grid-row-container site-header-focus-item ast-container&quot;]/div[@class=&quot;ast-builder-grid-row ast-builder-grid-row-has-sides ast-builder-grid-row-no-center&quot;]/div[@class=&quot;site-header-primary-section-left site-header-section ast-flex site-header-section-left&quot;]/div[@class=&quot;ast-builder-layout-element ast-flex site-header-focus-item&quot;]/div[@class=&quot;site-branding ast-site-identity&quot;]/span[@class=&quot;site-logo-img&quot;]/a[@class=&quot;custom-logo-link&quot;]/img[@class=&quot;custom-logo entered lazyloaded&quot;]</value>
      <webElementGuid>75f4468f-0836-4e60-ae74-43efc43467bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ast-desktop-header']/div/div/div/div/div/div/div/span/a/img</value>
      <webElementGuid>14054693-c8dc-40d2-a3a5-869ee21bc632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='RisQIT']</value>
      <webElementGuid>62f1e0e2-a047-44a0-878d-d25df8e17645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>250ebdcf-484d-4cf5-a6e4-0d52ef048bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2022/12/risqitlogo22-e1671873581192.png' and @alt = 'RisQIT']</value>
      <webElementGuid>7fd32425-d939-4e51-93a7-20698b59ffaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
