<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Software Testing</name>
   <tag></tag>
   <elementGuidId>1bb9b66f-b4a7-4414-ad49-a8c85f296124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-352']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-352 > a.menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>90a87ae3-bc18-4f9d-b3f7-245a679c6b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/software-testing/</value>
      <webElementGuid>8900dc62-ce6d-4a18-9b6a-1ac183c9dc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link</value>
      <webElementGuid>f93764b8-1bc5-44cb-95c9-828baa5c694d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Software Testing</value>
      <webElementGuid>cfa84582-f698-4dd0-b57d-eb60e7aa4c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-352&quot;)/a[@class=&quot;menu-link&quot;]</value>
      <webElementGuid>92c9fcc8-e7a5-400b-a2cf-76d40a3f2a7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-352']/a</value>
      <webElementGuid>4a382147-9817-4119-9c44-9f59f204e559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Software Testing')]</value>
      <webElementGuid>e9f65dad-b60b-4144-985a-b475ebfcd0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/software-testing/')]</value>
      <webElementGuid>8ffc5637-4f68-447c-be9d-6a583df96f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>8c24f5f6-1a30-42c4-906a-b6601f943ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/software-testing/' and (text() = 'Software Testing' or . = 'Software Testing')]</value>
      <webElementGuid>0769bca7-7de2-452f-a846-5633ff345019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
