<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Security en HackersTest (SHT)</name>
   <tag></tag>
   <elementGuidId>ab1fa15d-d114-42f7-8dad-57088448a8fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Security en HackersTest (SHT)' or . = 'Security en HackersTest (SHT)')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='post-322']/header/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.entry-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7ce3950d-f21e-4a80-ab33-4cea938bdcb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entry-title</value>
      <webElementGuid>aa6e8d1b-48e3-454b-b2c2-8beca8f83c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>headline</value>
      <webElementGuid>1950faff-3407-46dc-a2c5-785f51171287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Security en HackersTest (SHT)</value>
      <webElementGuid>153e5ff5-8931-434f-bba1-b25b3946aec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-322&quot;)/header[@class=&quot;entry-header ast-no-thumbnail&quot;]/h1[@class=&quot;entry-title&quot;]</value>
      <webElementGuid>4cc80665-1e24-4f62-ba6f-74bcbb69f3c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//*[@id='post-322']/header/h1</value>
      <webElementGuid>107ef2c9-e749-45cb-b471-ceadec3f8594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>d80c8fe7-5c4b-407e-bad8-c54c1eb24a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Security en HackersTest (SHT)' or . = 'Security en HackersTest (SHT)')]</value>
      <webElementGuid>45783dd6-5ffd-4f2c-b544-b29925dc147a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
