<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_play</name>
   <tag></tag>
   <elementGuidId>09153a00-19cb-46fa-b7b5-9d86375dd938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-367']/div/figure/div/div/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.play</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bff0d02d-02f3-427e-a802-c4d43c5addae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>play</value>
      <webElementGuid>ffd2ea67-26e3-4988-b02c-b44602245191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>play Youtube video</value>
      <webElementGuid>ac188556-9e80-451d-8a1a-6efb45ff4c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-367&quot;)/div[@class=&quot;entry-content clear&quot;]/figure[@class=&quot;wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-4-3 wp-has-aspect-ratio&quot;]/div[@class=&quot;wp-block-embed__wrapper&quot;]/div[@class=&quot;ast-oembed-container&quot;]/div[@class=&quot;rll-youtube-player&quot;]/div[1]/button[@class=&quot;play&quot;]</value>
      <webElementGuid>a11a0890-7b1f-4a51-9a56-525394efa6ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-367']/div/figure/div/div/div/div/button</value>
      <webElementGuid>4d258065-1b6a-4156-b371-e9b634308a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/div/div/div/button</value>
      <webElementGuid>182befc2-2528-4625-bf42-80c36dbc5b14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
