<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ytp-volume-slider-handle</name>
   <tag></tag>
   <elementGuidId>395d1a43-5a2f-4cae-8bb6-6767a06bea42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movie_player']/div[28]/div[2]/div/span/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ytp-volume-slider-handle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8fef5a7b-b854-4ef4-b823-b698ddb8881a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-volume-slider-handle</value>
      <webElementGuid>9c6c88ea-5a81-458a-b949-1c590584c52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movie_player&quot;)/div[@class=&quot;ytp-chrome-bottom ytp-volume-slider-active&quot;]/div[@class=&quot;ytp-chrome-controls&quot;]/div[@class=&quot;ytp-left-controls&quot;]/span[@class=&quot;ytp-volume-area&quot;]/div[@class=&quot;ytp-volume-panel ytp-volume-control-hover&quot;]/div[@class=&quot;ytp-volume-slider&quot;]/div[@class=&quot;ytp-volume-slider-handle&quot;]</value>
      <webElementGuid>3a63457f-747f-4b50-8a44-db550738a5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MenuTopbar/Page_Vacatures - RisQIT/iframe</value>
      <webElementGuid>e3b27cea-3037-44ad-b660-84b7bfed90f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movie_player']/div[28]/div[2]/div/span/div/div/div</value>
      <webElementGuid>6ac2222d-5782-4206-b4b9-1d677b07ccd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div</value>
      <webElementGuid>84648076-d759-467c-86c3-dd9f552afbf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
