<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>2e4e2216-e6d1-4d51-9178-134fc09d7b93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-367']/div/figure/div/div/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7b3311ed-4c22-4fef-8a26-572671b978bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/yusPA9NCltM?autoplay=1&amp;feature=oembed</value>
      <webElementGuid>c68d9e68-34ef-4ef7-8d23-eea7609d3367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>341056ab-4476-465d-8105-e4bf7c0eb792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>da061eaa-a58d-45b8-9e9e-2e3036cbf6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture</value>
      <webElementGuid>b0fd5763-465f-4c6d-ad11-1ab662a2c71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-367&quot;)/div[@class=&quot;entry-content clear&quot;]/figure[@class=&quot;wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-4-3 wp-has-aspect-ratio&quot;]/div[@class=&quot;wp-block-embed__wrapper&quot;]/div[@class=&quot;ast-oembed-container&quot;]/div[@class=&quot;rll-youtube-player&quot;]/iframe[1]</value>
      <webElementGuid>e24e2a25-4e76-43cc-ad14-085e0104f1cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-367']/div/figure/div/div/div/iframe</value>
      <webElementGuid>87cee429-2671-4a18-987d-6a63f507c3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>1d5c1d05-c032-41c6-a438-53583751ca3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://www.youtube.com/embed/yusPA9NCltM?autoplay=1&amp;feature=oembed']</value>
      <webElementGuid>da755097-c445-451a-a1f9-614f2865c435</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
