<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Menu_Blog</name>
   <tag></tag>
   <elementGuidId>3b1d235d-8b1a-473a-aa45-a943c9cd4bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-25778']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-25778 > a.menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5953ee8e-21b4-42aa-be63-d4e35ac77da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/blog/</value>
      <webElementGuid>cc6f397d-5e14-440d-bdf4-d9c0174df9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link</value>
      <webElementGuid>9a7b7e67-a4e7-4adf-aef4-ce79313ab782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blog</value>
      <webElementGuid>7daa17ed-b5e3-4792-97f0-6534dc9556c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-25778&quot;)/a[@class=&quot;menu-link&quot;]</value>
      <webElementGuid>eb2a7aa1-db98-4051-b9b6-e342f411c07a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-25778']/a</value>
      <webElementGuid>12f3f2d1-dfad-4317-bfae-442e7c34bf24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Blog')]</value>
      <webElementGuid>9104be3a-badb-404e-b6e0-cd074d4f1bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/blog/')]</value>
      <webElementGuid>30bd18a7-550d-4ac1-9df8-2ad815ce1db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>8c7894ff-2b64-4a5d-8623-e6430778e385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/blog/' and (text() = 'Blog' or . = 'Blog')]</value>
      <webElementGuid>9d22de92-b7a7-4706-9891-724f5219fe6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
