<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Menu_OverOns_SuperTester</name>
   <tag></tag>
   <elementGuidId>908e4c5f-691c-49cf-82eb-24a7f55a6e08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26103']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-364 > a.menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ef4aaae7-1fa3-4278-95ee-90dee90472e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/over-ons/kwaliteit/</value>
      <webElementGuid>d5873ce6-4362-44eb-8604-bd90741daeda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link</value>
      <webElementGuid>bcd8de8c-2546-470c-bcb2-08619d79375d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kwaliteit</value>
      <webElementGuid>9072f4b4-795e-4e8e-ad0a-6a63b903d2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-364&quot;)/a[@class=&quot;menu-link&quot;]</value>
      <webElementGuid>cf223fcc-ded3-4967-88c8-7e25013e936c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26103']/a</value>
      <webElementGuid>f55d73ce-418e-4f99-b97d-66feb9b45fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SuperTester')]</value>
      <webElementGuid>d5fd59fa-a918-45c9-bd45-1c276c24b5fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
