<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Logo</name>
   <tag></tag>
   <elementGuidId>8b8089b0-fcee-4a32-98a8-3485753749b4</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Home - RisQIT/img_custom-logo entered lazyloaded.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ast-desktop-header']/div/div/div/div/div/div/div/span/a/img</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Home - RisQIT/img_custom-logo entered lazyloaded.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.custom-logo.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>62a6d9cf-211c-4b49-b00f-315a260d7c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>174</value>
      <webElementGuid>e5410eb7-e8c4-4b61-91b1-ce73beec851e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>51</value>
      <webElementGuid>fd86dd8d-953d-4c54-8f1e-baffe19dc7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2022/12/risqitlogo22-e1671873581192.png</value>
      <webElementGuid>cee384ad-5fd2-4c27-9d3c-0a2c03c7b3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-logo entered lazyloaded</value>
      <webElementGuid>be1cfa02-fc2d-4f66-9732-c765aa27eb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>RisQIT</value>
      <webElementGuid>cffc3390-5a87-4081-84aa-ca7ea321eb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>6b6bc239-1e8b-40df-a8ff-ab236186e0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2022/12/risqitlogo22-e1671873581192.png</value>
      <webElementGuid>628f9c95-d0a6-4174-854c-f83536da7e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>c6778161-68ae-4ffe-ba86-070947f6e3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ast-desktop-header&quot;)/div[@class=&quot;ast-main-header-wrap main-header-bar-wrap&quot;]/div[@class=&quot;ast-primary-header-bar ast-primary-header main-header-bar site-header-focus-item&quot;]/div[@class=&quot;site-primary-header-wrap ast-builder-grid-row-container site-header-focus-item ast-container&quot;]/div[@class=&quot;ast-builder-grid-row ast-builder-grid-row-has-sides ast-builder-grid-row-no-center&quot;]/div[@class=&quot;site-header-primary-section-left site-header-section ast-flex site-header-section-left&quot;]/div[@class=&quot;ast-builder-layout-element ast-flex site-header-focus-item&quot;]/div[@class=&quot;site-branding ast-site-identity&quot;]/span[@class=&quot;site-logo-img&quot;]/a[@class=&quot;custom-logo-link&quot;]/img[@class=&quot;custom-logo entered lazyloaded&quot;]</value>
      <webElementGuid>13efecdb-2a0d-4264-aa62-96d93ccc1c58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ast-desktop-header']/div/div/div/div/div/div/div/span/a/img</value>
      <webElementGuid>f101e91c-2bd0-4dce-be44-79c96606f424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='RisQIT']</value>
      <webElementGuid>d05f5c01-82ac-4b5b-bcfa-43db29abd45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>17e9271d-ec69-463a-9bac-15091598bc68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2022/12/risqitlogo22-e1671873581192.png' and @alt = 'RisQIT']</value>
      <webElementGuid>90308ecc-b150-4399-8735-9dda69c45fda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
