<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chkbx_PrivacybeleidAkkoord</name>
   <tag></tag>
   <elementGuidId>117b9abc-73c8-48e3-8624-8f6f51f4e807</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wpcf7-f531-p518-o1']/form/p[7]/label/span/span/span/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.wpcf7-list-item-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7af5339-2fd5-4fab-95a2-f4638de7c932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-list-item-label</value>
      <webElementGuid>bd18c2f0-2040-4462-b950-0208c8d74fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ik heb het Privacybeleid gelezen en ga hiermee akkoord.</value>
      <webElementGuid>5d256e09-d606-4ce2-9557-41c948e4245c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f531-p518-o1&quot;)/form[@class=&quot;wpcf7-form init&quot;]/p[7]/label[1]/span[@class=&quot;wpcf7-form-control-wrap&quot;]/span[@class=&quot;wpcf7-form-control wpcf7-acceptance&quot;]/span[@class=&quot;wpcf7-list-item&quot;]/label[1]/span[@class=&quot;wpcf7-list-item-label&quot;]</value>
      <webElementGuid>1317052c-6137-440c-88fe-fd14c1094ab6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f531-p518-o1']/form/p[7]/label/span/span/span/label/span</value>
      <webElementGuid>9bc4c62a-9317-4838-8e0a-77e1cd665658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label/span</value>
      <webElementGuid>de8a6306-2ea8-404a-8cb8-ed260ad91a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ik heb het Privacybeleid gelezen en ga hiermee akkoord.' or . = 'Ik heb het Privacybeleid gelezen en ga hiermee akkoord.')]</value>
      <webElementGuid>9d38d45d-a9ae-4973-816b-e2a06976652b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
