<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_custom-logo entered lazyloaded</name>
   <tag></tag>
   <elementGuidId>81fc9c01-949b-41c6-9f70-dde12e22e4e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ast-mobile-header']/div/div/div/div/div/div/span/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.custom-logo.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a8b491bc-2677-4e51-9848-f062f1fb79c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>174</value>
      <webElementGuid>bc9c8532-9f9f-45ec-8bea-375e4c19c25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>51</value>
      <webElementGuid>7109daad-d01f-417a-aa21-fa879962a29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2022/12/risqitlogo22-e1671873581192.png</value>
      <webElementGuid>367008f4-1c5b-4ecb-85cc-bb728183b767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-logo entered lazyloaded</value>
      <webElementGuid>bd484ee6-2da5-4235-8e5a-314cd03241ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>RisQIT</value>
      <webElementGuid>e5248ac2-3097-4cf2-b3fb-981ade66cc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a0bde446-45b3-4594-b787-a80e01628064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2022/12/risqitlogo22-e1671873581192.png</value>
      <webElementGuid>80e0a04d-99d7-4681-b728-6aa672b83def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>329289d7-19a6-4f0a-83bc-c86c43adaf28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ast-mobile-header&quot;)/div[@class=&quot;ast-main-header-wrap main-header-bar-wrap&quot;]/div[@class=&quot;ast-primary-header-bar ast-primary-header main-header-bar site-primary-header-wrap site-header-focus-item ast-builder-grid-row-layout-default ast-builder-grid-row-tablet-layout-default ast-builder-grid-row-mobile-layout-default&quot;]/div[@class=&quot;ast-builder-grid-row ast-builder-grid-row-has-sides ast-builder-grid-row-no-center&quot;]/div[@class=&quot;site-header-primary-section-left site-header-section ast-flex site-header-section-left&quot;]/div[@class=&quot;ast-builder-layout-element ast-flex site-header-focus-item&quot;]/div[@class=&quot;site-branding ast-site-identity&quot;]/span[@class=&quot;site-logo-img&quot;]/a[@class=&quot;custom-logo-link&quot;]/img[@class=&quot;custom-logo entered lazyloaded&quot;]</value>
      <webElementGuid>5ce841b4-36dd-4706-8591-1496ba3df294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ast-mobile-header']/div/div/div/div/div/div/span/a/img</value>
      <webElementGuid>c52b45ca-dba2-4bb8-9c32-dd346433f719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='RisQIT'])[2]</value>
      <webElementGuid>3422a61b-5e18-42f0-92c2-3d5eb0a819d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/span/a/img</value>
      <webElementGuid>3456d93f-98f4-459e-a557-84a05b65f2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://nlrisqitww-chaca.savviihq.com/wp-content/uploads/2022/12/risqitlogo22-e1671873581192.png' and @alt = 'RisQIT']</value>
      <webElementGuid>2fe677c6-ca7b-4e81-b4f4-e4b951073755</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
