<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_opmerking</name>
   <tag></tag>
   <elementGuidId>0517b569-db2a-4870-adcd-eba7f8e5936b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='opmerking']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;opmerking&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>348a43e1-443f-40d8-b560-53e1e40a6b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>37419e84-22e9-485e-9f9a-b91dc5ac130c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ab3de925-ab18-48fa-82ab-3b0911ab930e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-textarea wpcf7-validates-as-required</value>
      <webElementGuid>84c468e9-94c6-484c-8344-0bf6a05ed2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e4f82c5a-2d89-4e2b-94ac-12f2625e6f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>da1fbf92-599c-4e58-8f07-b37d4feab106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>opmerking</value>
      <webElementGuid>cc3c077a-2ac7-4ce3-8fda-20cf616f786c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f531-p518-o1&quot;)/form[@class=&quot;wpcf7-form init&quot;]/p[6]/label[1]/span[@class=&quot;wpcf7-form-control-wrap&quot;]/textarea[@class=&quot;wpcf7-form-control wpcf7-textarea wpcf7-validates-as-required&quot;]</value>
      <webElementGuid>4256b067-1b42-40be-8eff-b5502439bfc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='opmerking']</value>
      <webElementGuid>85207e1a-ad6c-44cb-9d50-4eb001026f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f531-p518-o1']/form/p[6]/label/span/textarea</value>
      <webElementGuid>d30b263e-fe8d-4777-857c-02dc54bea76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>fa18a374-ed23-4481-b923-b64919f48b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'opmerking']</value>
      <webElementGuid>18c3724c-2d41-44f8-ba3f-837ecaab9939</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
