<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_ast-mobile-svg ast-close-svg</name>
   <tag></tag>
   <elementGuidId>4debc6d5-4e6c-4b0a-8729-549ef236d4b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ast-svg-iconset > span.ahfb-svg-iconset.ast-inline-flex.svg-baseline > svg.ast-mobile-svg.ast-close-svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>2d8e2c14-0c16-44fb-af2f-7b32a303c8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ast-mobile-svg ast-close-svg</value>
      <webElementGuid>1697dcfe-978a-41d6-9246-d9c3f0a72814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>8bd23c26-28a7-4553-98ab-543517c55bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>ca148ab7-50b3-479c-a44b-81beea5ad47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>6cd186d0-0ee6-457e-9568-17771cb97d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>6399a946-2bcc-49a6-a972-890faf8deb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>8f62d558-32e7-47a6-b0f9-ec568b0caea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>8ddf09c0-5f8f-49f6-abba-52e21026c4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-toggle-close&quot;)/span[@class=&quot;ast-svg-iconset&quot;]/span[@class=&quot;ahfb-svg-iconset ast-inline-flex svg-baseline&quot;]/svg[@class=&quot;ast-mobile-svg ast-close-svg&quot;]</value>
      <webElementGuid>c0358c8d-e4e8-477d-b00b-374faf1b7d6b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
