<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_ast-mobile-svg ast-menu-svg</name>
   <tag></tag>
   <elementGuidId>f8c1eece-27c7-4ac3-a449-f11f02f72659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.ast-mobile-svg.ast-menu-svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>a117b077-c273-4019-b754-006f301fee19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ast-mobile-svg ast-menu-svg</value>
      <webElementGuid>56216d98-80c0-4bde-a056-ddb06af4b7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>c4ead1fc-3276-48e2-960b-fdbb86db02cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>bd25efdb-25d7-4522-a557-ac8e92d01ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>17ae729a-7532-4003-a4ff-0087debd5be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>dd5ebd1e-260d-4618-a1b4-844a931294af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>ccc3138f-8d7f-4457-b8f5-e31b6c93d312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>3dcb4881-e0a4-4659-86ec-0acf2b12c0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ast-mobile-header&quot;)/div[@class=&quot;ast-main-header-wrap main-header-bar-wrap&quot;]/div[@class=&quot;ast-primary-header-bar ast-primary-header main-header-bar site-primary-header-wrap site-header-focus-item ast-builder-grid-row-layout-default ast-builder-grid-row-tablet-layout-default ast-builder-grid-row-mobile-layout-default&quot;]/div[@class=&quot;ast-builder-grid-row ast-builder-grid-row-has-sides ast-builder-grid-row-no-center&quot;]/div[@class=&quot;site-header-primary-section-right site-header-section ast-flex ast-grid-right-section&quot;]/div[@class=&quot;ast-builder-layout-element ast-flex site-header-focus-item&quot;]/div[@class=&quot;ast-button-wrap&quot;]/button[@class=&quot;menu-toggle main-header-menu-toggle ast-mobile-menu-trigger-fill&quot;]/span[@class=&quot;mobile-menu-toggle-icon&quot;]/span[@class=&quot;ahfb-svg-iconset ast-inline-flex svg-baseline&quot;]/svg[@class=&quot;ast-mobile-svg ast-menu-svg&quot;]</value>
      <webElementGuid>6ac2a01f-fa20-43d3-96ae-dbd7579bd7d0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
