<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Missie  Visie</name>
   <tag></tag>
   <elementGuidId>0b3fc432-8e22-45c8-bf7f-cb609daec7ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-365']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-365 > a.menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a4cad323-796f-472b-a988-4625f439ea58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/over-ons/missie-visie/</value>
      <webElementGuid>6592f127-f9b9-482b-8d36-cb0a819dde0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link</value>
      <webElementGuid>39cff26c-4374-47ee-984d-2d0848311111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Missie &amp; Visie</value>
      <webElementGuid>e060619f-7f85-4e27-887e-83be65ae0378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-365&quot;)/a[@class=&quot;menu-link&quot;]</value>
      <webElementGuid>80e172e3-6419-4e9f-9cb1-d4dcbe751dd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-365']/a</value>
      <webElementGuid>0960c484-237b-4494-bb8b-55385f55d1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Missie &amp; Visie')]</value>
      <webElementGuid>e34af063-e443-47ea-9e39-f3d35fc31ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/over-ons/missie-visie/')]</value>
      <webElementGuid>b597e5ac-543a-421f-bf03-2886212637c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>0e968bb9-67c1-45b1-9aa1-156f37668ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/over-ons/missie-visie/' and (text() = 'Missie &amp; Visie' or . = 'Missie &amp; Visie')]</value>
      <webElementGuid>b8b33e19-2868-4ccf-875e-37641ca30a46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
