<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you for subscribing</name>
   <tag></tag>
   <elementGuidId>46cb281c-102c-44b2-9004-ca00ee096b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mce-success-response']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mce-success-response</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1be1e83f-3da1-496f-a7cd-25a164206b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>response</value>
      <webElementGuid>dc6e15b1-ba22-49b4-926a-9bdfc9811644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mce-success-response</value>
      <webElementGuid>69bd1601-f0fc-40b0-8fe6-39c1edec44c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-recent-on-screen32063062_29</name>
      <type>Main</type>
      <value>19432</value>
      <webElementGuid>789a1457-b805-433c-91a7-b2b9e47a6700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-first-on-screen32063062_29</name>
      <type>Main</type>
      <value>19432</value>
      <webElementGuid>5b5ef35f-8312-4e38-b85f-ea409d3fd84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-total-visible-time32063062_29</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>9d7b7a12-05d7-4771-b000-3edcba0b58fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-has-fired32063062_29</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fddd1e5e-d9a8-48d4-9abc-75f0ca15915f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for subscribing!</value>
      <webElementGuid>0c8cb2d3-3a8f-47cd-9745-b2c6d756364d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mce-success-response&quot;)</value>
      <webElementGuid>e390efc4-e651-4dc6-8447-7cfc71ff1421</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mce-success-response']</value>
      <webElementGuid>6847bdb4-0436-4507-9ab5-c627fe19ee70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mce-responses']/div[2]</value>
      <webElementGuid>d8c6775d-a438-47ab-870e-e29c675cc46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]</value>
      <webElementGuid>e13f0daf-3088-4227-aac4-128c916280fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mce-success-response' and (text() = 'Thank you for subscribing!' or . = 'Thank you for subscribing!')]</value>
      <webElementGuid>d8a26b9a-ff29-4642-9aae-a688e9a96d86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
