<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Whitepaper SuperTester</name>
   <tag></tag>
   <elementGuidId>bacee14a-f601-4cea-9b3a-ddc80f9de528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-680']/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.has-text-align-center.has-ast-global-color-5-color.has-text-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>8c0e68f5-14d1-4027-babc-268ad1820a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>has-text-align-center has-ast-global-color-5-color has-text-color</value>
      <webElementGuid>c2eaef71-f582-48bf-9c1f-931b9544eefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Whitepaper SuperTester</value>
      <webElementGuid>d9500339-3e26-4c30-ab32-caaed51ab2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-680&quot;)/div[@class=&quot;entry-content clear&quot;]/div[@class=&quot;wp-block-cover alignfull&quot;]/div[@class=&quot;wp-block-cover__inner-container&quot;]/h1[@class=&quot;has-text-align-center has-ast-global-color-5-color has-text-color&quot;]</value>
      <webElementGuid>eb4bff43-0758-4703-a5c2-f4675fd0dbad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-680']/div/div/div/h1</value>
      <webElementGuid>9b2b1c2e-089e-4aaa-8c13-1196dc139a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>11374eda-6c21-441b-9b3c-58118ce8997b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Whitepaper SuperTester' or . = 'Whitepaper SuperTester')]</value>
      <webElementGuid>9a848996-e699-4f75-a9b3-130f85113e97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
