<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_subscribe</name>
   <tag></tag>
   <elementGuidId>33545e37-74e5-4b31-be81-9059c5c0b7c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mc-embedded-subscribe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mc-embedded-subscribe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed2ffb13-052a-4f61-8f1b-0b9d5f8d6eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4077f8a3-1546-4284-9f41-c92fa44a2e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Download whitepaper</value>
      <webElementGuid>e4adfdcf-1b94-40a6-8dee-56ff92b9f758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subscribe</value>
      <webElementGuid>d77a7e34-d35e-4c5c-9afc-3a066a8c15c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mc-embedded-subscribe</value>
      <webElementGuid>659f07ce-7a5d-449a-9dbd-62c5b856762f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d39067b-4d83-4536-813a-cfc7ea12e1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mc-embedded-subscribe&quot;)</value>
      <webElementGuid>139d4215-394a-4c8d-a053-b61cc76e2ee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mc-embedded-subscribe']</value>
      <webElementGuid>c563ebd3-a4e3-464e-b666-18d1d74aaae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mc_embed_signup_scroll']/div[9]/input</value>
      <webElementGuid>861bb021-475e-41c7-b3f5-7e24ba4abe9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>2ad7fd5c-745e-49d8-b197-c5ce57ee30bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'subscribe' and @id = 'mc-embedded-subscribe']</value>
      <webElementGuid>b336162c-c164-4155-b678-a90d34df3343</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
