<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BEDRIJF</name>
   <tag></tag>
   <elementGuidId>87cd0381-044d-480e-985c-66c195a17fbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mce-BEDRIJF']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mce-BEDRIJF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcaf53a0-69e2-4508-b328-3aaab4119eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb02f191-1fb6-4344-bfc9-c004bbb3fb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BEDRIJF</value>
      <webElementGuid>e95fd834-fe0f-45b1-97c6-e5bdc28dd7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>92f896b7-bee9-48a3-9209-74e6a0ddbbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mce-BEDRIJF</value>
      <webElementGuid>0e5c31a0-392b-4c09-a819-3cc232e937ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5d7bba65-cba7-43c1-875c-9f159a087dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mce-BEDRIJF&quot;)</value>
      <webElementGuid>7a01b9d6-17b1-4a72-b3a4-9244df7affa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mce-BEDRIJF']</value>
      <webElementGuid>2553b010-19f5-4328-a41f-fe2e8ef14266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mc_embed_signup_scroll']/div[6]/input</value>
      <webElementGuid>948a88ff-eff1-4ad6-a772-b80f7949a871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>077c5bfa-7375-4eb8-993d-16c75306924c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BEDRIJF' and @id = 'mce-BEDRIJF']</value>
      <webElementGuid>112ec865-4ce9-4e17-b524-f9d3f46f2eee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
