<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Voornaam</name>
   <tag></tag>
   <elementGuidId>d3d8ddf6-a73b-43bb-9cc1-e3e37fb010bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mc_embed_signup_scroll']/div[4]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bf92aea3-3ef4-45a1-8219-3a9be0fec524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>mce-FNAME</value>
      <webElementGuid>f43bec5e-347b-4203-922e-0ca2e51a8a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Voornaam  *
</value>
      <webElementGuid>2d8236e5-ff43-4380-a222-e39998773509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mc_embed_signup_scroll&quot;)/div[@class=&quot;mc-field-group&quot;]/label[1]</value>
      <webElementGuid>30b95356-16fe-4537-92e0-5cf8d4df30d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mc_embed_signup_scroll']/div[4]/label</value>
      <webElementGuid>a18f533c-224b-4ea1-8104-3a4d8b53b696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label</value>
      <webElementGuid>3c15baff-c75e-45c5-b329-1bd26e2ce424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Voornaam  *
' or . = 'Voornaam  *
')]</value>
      <webElementGuid>73a38ec2-1515-4695-a8fd-3bb5f7e31850</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
