<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SuperTester</name>
   <tag></tag>
   <elementGuidId>4e275f39-484b-4969-8b51-11567cb950b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26103']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26103 > a.menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b9ddc975-ea31-4164-98b4-fdda302dd899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/supertester/</value>
      <webElementGuid>5c175eb5-d2e7-45dc-a447-a38d7dd49daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link</value>
      <webElementGuid>51691ba9-756a-4aa2-af6c-016b2756ce8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SuperTester</value>
      <webElementGuid>b6fc5278-bee8-4ab5-88a2-a61b92f15328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26103&quot;)/a[@class=&quot;menu-link&quot;]</value>
      <webElementGuid>9d5d0afe-9df1-4e46-aaaf-a315e1739901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26103']/a</value>
      <webElementGuid>aa5af5c1-5085-4fe7-a2dd-4d5b2a1d1e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SuperTester')]</value>
      <webElementGuid>a8655c1b-50d1-42ee-8b5e-31fd1072868b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/supertester/')]</value>
      <webElementGuid>4ffdba5b-47c0-4de7-9aed-8a3f081cf2d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[3]/a</value>
      <webElementGuid>de93e788-9cbc-40c1-9e32-edfd30884ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/supertester/' and (text() = 'SuperTester' or . = 'SuperTester')]</value>
      <webElementGuid>62ca6b60-38b0-4ef1-bef6-128cf5dd9340</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
