<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Menu_OverOns_SuperTester</name>
   <tag></tag>
   <elementGuidId>77a3aec5-24e3-498a-8f76-08948c03363d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26103']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26103 > a.menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>083208ef-5831-4747-bb41-6b7fa51fed08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/supertester/</value>
      <webElementGuid>e6cf32ef-fd40-4064-a682-c3b537996c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link</value>
      <webElementGuid>8c5d9ade-e017-4401-aa24-520326f7fbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SuperTester</value>
      <webElementGuid>695791a7-6187-4cce-ae02-2407d88de97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26103&quot;)/a[@class=&quot;menu-link&quot;]</value>
      <webElementGuid>32a20927-f42e-420c-8299-65d306fef53c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26103']/a</value>
      <webElementGuid>d84393b7-bcd1-4044-b838-5446faf79a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SuperTester')]</value>
      <webElementGuid>e935b368-cf8f-4512-a1b0-1cb28c1f4a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/supertester/')]</value>
      <webElementGuid>495a41f6-04c9-49e3-a6f2-437cd4b3c1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[3]/a</value>
      <webElementGuid>e7f8a97e-3897-4105-a30a-9e568fe38109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/supertester/' and (text() = 'SuperTester' or . = 'SuperTester')]</value>
      <webElementGuid>0963d00c-06cf-466f-ad22-4a4d00679368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
