<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Menu_Vacatures</name>
   <tag></tag>
   <elementGuidId>2d49a129-afe6-4393-985a-057b45958b5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-369']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-369 > a.menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64f24868-e4c8-4ece-b53f-a91e98f3ccc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/vacatures/</value>
      <webElementGuid>d8963d3e-6a08-475d-b58c-c72d3833a37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link</value>
      <webElementGuid>9d231132-4b98-47e3-82ca-8c0f62f05ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vacatures</value>
      <webElementGuid>9b5933c1-c2e0-46b0-acf6-a7eeca052648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-369&quot;)/a[@class=&quot;menu-link&quot;]</value>
      <webElementGuid>5c1d6043-cb3d-48f7-a089-fdf6e14649b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-369']/a</value>
      <webElementGuid>ec8cadef-5cd2-474c-bca4-50293dd23291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vacatures')]</value>
      <webElementGuid>a35377a5-c9d8-4ecb-b82e-02e9271b13ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/vacatures/')]</value>
      <webElementGuid>ab7c8cc0-9bc2-49f2-bc3d-19173f7964e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>068cf421-8e07-4ed1-9e7e-389427066625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/vacatures/' and (text() = 'Vacatures' or . = 'Vacatures')]</value>
      <webElementGuid>26c8c462-a730-41c2-967c-8ebf5469d8fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
