<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Menu_Diensten_UXLab</name>
   <tag></tag>
   <elementGuidId>0b27846b-cd4f-4866-8f90-d92a28cbcba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-350']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-350 > a.menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>052edb7c-08dc-41ef-8704-c5ad927d5632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nlrisqitww-chaca.savviihq.com/ux-lab/</value>
      <webElementGuid>741c7b4b-d965-416f-a0c5-d3b75c677e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link</value>
      <webElementGuid>9647ee75-1bc7-4e2e-a07a-8d9e055fb8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UX Lab</value>
      <webElementGuid>7a30511e-de65-411a-a8b3-d0e8d3e6b045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-350&quot;)/a[@class=&quot;menu-link&quot;]</value>
      <webElementGuid>2db17816-5ba7-45dd-a81b-62ed2c04cecb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-350']/a</value>
      <webElementGuid>fa88d46f-df17-4736-b992-5face919e20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'UX Lab')]</value>
      <webElementGuid>0f820315-0eb8-4f3b-8377-95fe44141dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nlrisqitww-chaca.savviihq.com/ux-lab/')]</value>
      <webElementGuid>b009b35e-ebe8-422b-9f33-2499a66eeaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[3]/a</value>
      <webElementGuid>5c29b2f3-48c9-478a-b869-0e74ad7ed1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nlrisqitww-chaca.savviihq.com/ux-lab/' and (text() = 'UX Lab' or . = 'UX Lab')]</value>
      <webElementGuid>d25a80dc-f8b2-45f8-970a-5a74301b87ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
